tap "dagger/tap"
tap "fluxcd/tap"
tap "hashicorp/tap"
tap "helmwave/tap"
tap "loft-sh/tap"
tap "siderolabs/tap"
tap "stefanprodan/tap"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Automate deployment, configuration, and upgrading
brew "ansible"
# Checks ansible playbooks for practices and behaviour
brew "ansible-lint"
# Perf monitoring CLI tool for Apple Silicon
brew "asitop"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# CLI to install, manage & troubleshoot Kubernetes clusters running Cilium
brew "cilium-cli"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Diff that understands syntax
brew "difftastic"
# Utilities for the ext2, ext3, and ext4 file systems
brew "e2fsprogs"
# Modern, maintained replacement for ls
brew "eza"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Play, record, convert, and stream select audio and video codecs
brew "ffmpeg"
# Banner-like program prints strings as ASCII art
brew "figlet"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Open-source GitLab command-line tool
brew "glab"
# GNU Privacy Guard (OpenPGP)
brew "gnupg"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Command-line Golang template processor
brew "gomplate"
# GNU grep, egrep and fgrep
brew "grep"
# Smarter Dockerfile linter to validate best practices
brew "hadolint"
# Kubernetes package manager
brew "helm"
# HTTP load generator, ApacheBench (ab) replacement
brew "hey"
# Text-based UI library
brew "ncurses"
# Improved top (interactive process viewer)
brew "htop"
# Network, Service & Security Observability for Kubernetes using eBPF
brew "hubble"
# Client library for huggingface.co hub
brew "huggingface-cli"
# Calculate various network masks, etc. from a given IP address
brew "ipcalc"
# Update of iperf: measures TCP, UDP, and SCTP bandwidth
brew "iperf3"
# Istio configuration command-line utility
brew "istioctl"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Kubernetes command-line interface
brew "kubernetes-cli"
# Template-free customization of Kubernetes YAML manifests
brew "kustomize"
# TUI for logs from journalctl, file system, Docker, Podman and Kubernetes pods
brew "lazyjournal"
# Mac App Store command-line interface
brew "mas"
# Terminal-based visual file manager
brew "midnight-commander"
# Polyglot runtime manager (asdf rust clone)
brew "mise"
# Free (GNU) replacement for the Pico text editor
brew "nano"
# Python package management tool
brew "poetry"
# Monitor data's progress through a pipe
brew "pv"
# Extremely fast Python linter, written in Rust
brew "ruff"
# Safe, concurrent, practical language
brew "rust"
# 7-Zip is a file archiver with a high compression ratio
brew "sevenzip"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Fuzzy Finder in rust!
brew "sk"
# Editor of encrypted files
brew "sops"
# Non-interactive SSH password auth
brew "sshpass"
# Cross-shell prompt for astronauts
brew "starship"
# CLI for out-of-band management of Kubernetes nodes created by Talos
brew "talosctl"
# User interface to the TELNET protocol
brew "telnet"
# Thin wrapper for Terraform e.g. for locking state
brew "terragrunt"
# Powerful free data recovery utility
brew "testdisk"
# Code-search similar to ack
brew "the_silver_searcher"
# Terminal multiplexer
brew "tmux"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Internet file retriever
brew "wget"
# Process YAML, JSON, XML, CSV and properties documents from the CLI
brew "yq"
# Feature-rich command-line audio/video downloader
brew "yt-dlp"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# Dagger is an integrated platform to orchestrate the delivery of applications
brew "dagger/tap/dagger"
# Flux CLI
brew "fluxcd/tap/flux"
# Packer
brew "hashicorp/tap/packer"
# Terraform
brew "hashicorp/tap/terraform"
# Vault
brew "hashicorp/tap/vault"
# Helmwave is true release management for helm
brew "helmwave/tap/helmwave"
# Creates fully functional virtual k8s cluster inside host k8s cluster's namespace
brew "loft-sh/tap/vcluster"
# CLI for Omni - SaaS-simple deployment of Kubernetes - on your own hardware.
brew "siderolabs/tap/omnictl"
# Timoni CLI
brew "stefanprodan/tap/timoni"
# Enable Windows-like alt-tab
cask "alt-tab"
# OpenAI's coding agent that runs in your terminal
cask "codex"
# Screen capturing tool
cask "cleanshot"
# Server and cloud storage browser
cask "cyberduck"
# Photography workflow application and raw developer
cask "darktable"
# Universal database tool and SQL client
cask "dbeaver-community"
# Disk usage utility
cask "disk-inventory-x"
cask "font-fira-code-nerd-font"
cask "font-meslo-lg-nerd-font"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Open-source video transcoder
cask "handbrake-app"
# Menu bar application that displays the CPU speed limit due to thermal issues
cask "hot"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Menu bar calendar
cask "itsycal"
# Password manager app
cask "keepassxc"
# Clipboard manager
cask "maccy"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Android file transfer
cask "openmtp"
# Archive manager for data compression and backups
cask "rar"
# RAW photo processor
cask "rawtherapee"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Media player based on MPlayer and mplayer2
cask "stolendata-mpv"
# Text editor for code, markup and prose
cask "sublime-text"
# Open-source BitTorrent client
cask "transmission"
# Network protocol analyzer
cask "wireshark-app"
mas "AmorphousDiskMark", id: 1168254295
mas "Bee DICOM Viewer", id: 1590273176
mas "Blackmagic Disk Speed Test", id: 425264550
mas "Happ", id: 6746188973
mas "Numbers", id: 409203825
mas "One Thing", id: 1604176982
mas "Outline", id: 1356178125
mas "Pages", id: 409201541
mas "Qi FM", id: 1479696191
mas "Todoist", id: 585829637
mas "Windows App", id: 1295203466
mas "Xcode", id: 497799835
vscode "4ops.packer"
vscode "anysphere.pyright"
vscode "charliermarsh.ruff"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "github.vscode-github-actions"
vscode "gitlab.gitlab-workflow"
vscode "golang.go"
vscode "ms-azuretools.vscode-docker"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.remote-explorer"
vscode "redhat.vscode-yaml"
vscode "rust-lang.rust-analyzer"
vscode "sztheory.vscode-packer-powertools"
vscode "tim-koehler.helm-intellisense"
vscode "vscode-icons-team.vscode-icons"
vscode "zhuangtongfa.material-theme"
go "github.com/go-delve/delve/cmd/dlv"
go "golang.org/x/tools/gopls"
go "honnef.co/go/tools/cmd/staticcheck"
