[tasks."python"]
description = "Run Python routines"
depends = [
  "python:*",
]

[tasks."python:format"]
description = "Run all Python formatters"
tools.fd = "latest"
depends = [
  "python:format:*"
]

[tasks."python:lint"]
description = "Run all Python linters"
tools.fd = "latest"
wait_for = [
  "python:format:*"
]
depends = [
  "python:lint:*"
]

[tasks."python:lint:ruff"]
description = "Run Ruff (linter)"
tools.ruff = "latest"
tools.fd = "latest"
run = "9fl -a dots | xargs ruff check"

[tasks."python:lint:mypy"]
description = "Run MyPy"
tools."pipx:mypy" = "latest"
tools.fd = "latest"
run = "9fl -a dots | xargs -n 1 mypy"

[tasks."python:format:ruff"]
description = "Run Ruff (format)"
tools.ruff = "latest"
tools.fd = "latest"
run = "9fl -a dots | xargs ruff format"
