tap "hashicorp/tap"
tap "helmwave/tap"
tap "siderolabs/tap"
tap "stefanprodan/tap"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Automate deployment, configuration, and upgrading
brew "ansible"
# Checks ansible playbooks for practices and behaviour
brew "ansible-lint"
# GitOps Continuous Delivery for Kubernetes
brew "argocd"
# Text-based UI library
brew "ncurses"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Manage your dotfiles across multiple diverse machines, securely
brew "chezmoi"
# CLI to install, manage & troubleshoot Kubernetes clusters running Cilium
brew "cilium-cli"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Utilities for the ext2, ext3, and ext4 file systems
brew "e2fsprogs"
# Modern, maintained replacement for ls
brew "eza"
# Play, record, convert, and stream select audio and video codecs
brew "ffmpeg"
# Banner-like program prints strings as ASCII art
brew "figlet"
# Collection of GNU find, xargs, and locate
brew "findutils"
# Lightweight scripting language for querying databases
brew "flux"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU awk utility
brew "gawk"
# Interact with Google Gemini AI models from the command-line
brew "gemini-cli"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Audit git repos for secrets
brew "gitleaks"
# Open-source GitLab command-line tool
brew "glab"
# Command-line option parsing utility
brew "gnu-getopt"
# C code prettifier
brew "gnu-indent"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# GNU version of the tar archiving utility
brew "gnu-tar"
# GNU implementation of time utility
brew "gnu-time"
# GNU unit conversion tool
brew "gnu-units"
# GNU implementation of which utility
brew "gnu-which"
# Common error values for all GnuPG components
brew "libgpg-error"
# GNU Privacy Guard (OpenPGP)
brew "gnupg"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# GNU grep, egrep and fgrep
brew "grep"
# Kubernetes package manager
brew "helm"
# HTTP load generator, ApacheBench (ab) replacement
brew "hey"
# Client library for huggingface.co hub
brew "hf"
# Improved top (interactive process viewer)
brew "htop"
# Network, Service & Security Observability for Kubernetes using eBPF
brew "hubble"
# Tools and libraries to manipulate images in select formats
brew "imagemagick"
# Calculate various network masks, etc. from a given IP address
brew "ipcalc"
# Update of iperf: measures TCP, UDP, and SCTP bandwidth
brew "iperf3"
# Istio configuration command-line utility
brew "istioctl"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Kubernetes command-line interface
brew "kubernetes-cli"
# Tool that can switch between kubectl contexts easily and create aliases
brew "kubectx"
# Template-free customization of Kubernetes YAML manifests
brew "kustomize"
# Simple terminal UI for git commands
brew "lazygit"
# TUI for logs from journalctl, file system, Docker, Podman and Kubernetes pods
brew "lazyjournal"
# Pager program similar to more
brew "less"
# Apple Silicon Monitor Top written in Go Lang
brew "mactop"
# Mac App Store command-line interface
brew "mas"
# Terminal-based visual file manager
brew "midnight-commander"
# Polyglot runtime manager (asdf rust clone)
brew "mise"
# Free (GNU) replacement for the Pico text editor
brew "nano"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# TUI log viewer with timeline histogram and no central server
brew "nerdlog"
# OpenBSD freely-licensed SSH connectivity tools
brew "openssh"
# Monitor data's progress through a pipe
brew "pv"
# Utility that provides fast incremental file transfer
brew "rsync"
# 7-Zip is a file archiver with a high compression ratio
brew "sevenzip"
# Fuzzy Finder in rust!
brew "sk"
# Editor of encrypted files
brew "sops"
# Non-interactive SSH password auth
brew "sshpass"
# Cross-shell prompt for astronauts
brew "starship"
# CLI for out-of-band management of Kubernetes nodes created by Talos
brew "talosctl"
# User interface to the TELNET protocol
brew "telnet"
# Thin wrapper for Terraform e.g. for locking state
brew "terragrunt"
# Powerful free data recovery utility
brew "testdisk"
# Code-search similar to ack
brew "the_silver_searcher"
# Terminal multiplexer
brew "tmux"
# Creates fully functional virtual k8s cluster inside host k8s cluster's namespace
brew "vcluster"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Internet file retriever
brew "wget"
# Feature-rich command-line audio/video downloader
brew "yt-dlp"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# Packer
brew "hashicorp/tap/packer"
# Terraform
brew "hashicorp/tap/terraform"
# Vault
brew "hashicorp/tap/vault"
# Helmwave is true release management for helm
brew "helmwave/tap/helmwave"
# CLI for Omni - SaaS-simple deployment of Kubernetes - on your own hardware.
brew "siderolabs/tap/omnictl"
# Enable Windows-like alt-tab
cask "alt-tab"
# Server and cloud storage browser
cask "cyberduck"
# Photography workflow application and raw developer
cask "darktable"
# Universal database tool and SQL client
cask "dbeaver-community"
# Disk usage utility
cask "disk-inventory-x"
cask "font-fira-code-nerd-font"
cask "font-meslo-lg-nerd-font"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Open-source video transcoder
cask "handbrake-app"
# UI for Kubernetes
cask "headlamp"
# Menu bar application that displays the CPU speed limit due to thermal issues
cask "hot"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Menu bar calendar
cask "itsycal"
# Password manager app
cask "keepassxc"
# Clipboard manager
cask "maccy"
# Android file transfer
cask "openmtp"
# Archive manager for data compression and backups
cask "rar"
# RAW photo processor
cask "rawtherapee"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Media player based on MPlayer and mplayer2
cask "stolendata-mpv"
# Text editor for code, markup and prose
cask "sublime-text"
# Open-source BitTorrent client
cask "transmission"
# Network protocol analyzer
cask "wireshark-app"
vscode "4ops.packer"
vscode "blueglassblock.better-json5"
vscode "charliermarsh.ruff"
vscode "chouzz.vscode-better-align"
vscode "docker.docker"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "github.copilot-chat"
vscode "github.vscode-github-actions"
vscode "gitlab.gitlab-workflow"
vscode "golang.go"
vscode "hashicorp.terraform"
vscode "hverlin.mise-vscode"
vscode "irongeek.vscode-env"
vscode "mhutchie.git-graph"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-python.black-formatter"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.remote-explorer"
vscode "redhat.ansible"
vscode "redhat.vscode-yaml"
vscode "rust-lang.rust-analyzer"
vscode "signageos.signageos-vscode-sops"
vscode "sztheory.vscode-packer-powertools"
vscode "tamasfe.even-better-toml"
vscode "tekumara.typos-vscode"
vscode "tim-koehler.helm-intellisense"
vscode "tyriar.sort-lines"
vscode "vscode-icons-team.vscode-icons"
vscode "zhuangtongfa.material-theme"
go "cmd/go"
go "cmd/gofmt"
